### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by ungoldman** [noffle/hyperpad#1]
Hi @noffle! I'm trying to get this working using the link you sent me a while back -- http://hyperpad.io/?doc=hi-nate. Not seeing anything synced between two chrome tabs (one incognito, one regular). Not seeing anything persist on reload either. What's the expected behavior? Am I doing it wrong?

**Comment by hackergrrl** [comment]
Hey! Thank you for trying out hyperpad. :pray: 

You're totally right: it's not reading the hyper-string from indexeddb! It's working on localhost though, so I wonder if it's something related to the domain & access. I'll dig on this -- thanks for reporting!

**Comment by hackergrrl** [comment]
@ungoldman Hey Nate! It's been a while, but I spent some time today fixing some bugs across the module stack. (It probably also helped that I'm running my own signalhub now.) Feel like taking it for a spin again?

**Comment by ungoldman** [comment]
Looks like in a single chrome tab things are persisting! However, still some unexpected behavior:
1. I open a window, load http://hyperpad.io/?doc=hi-nate. Stuff is there. I edit, close, reopen, my edits are still there. Yay!
2. I open an incognito window, load http://hyperpad.io/?doc=hi-nate. Nothing is here. Hmm...
3. I reload the incognito window, stuff from (1) is now showing up and changes are syncing between the two. Yay!

**Comment by hackergrrl** [comment]
Awesome! I'm glad (1) is working at least. Thank you for trying this again.

If you try (2) again but wait for ~10 seconds, does anything appear? It takes a while for peers to connect to the signalling server, hook up to each other, and perform sync. I'll enable logging now, so if you try again you ought to see a bit more information in the web console.

**Comment by ungoldman** [comment]
Hi @noffle! Catching up on issues...

Had a chance to try what you asked, still not seeing text replicate on first visit in incognito mode, but it DOES look like there's a lot of activity from what's happening in the console.

Here's a dump of the log: https://gist.github.com/ungoldman/9c86965509b26a3af4294dc6cdb635c8

Note this is all happening within the first few seconds of loading the page.

**Comment by hackergrrl** [comment]
Thanks @ungoldman! It looks like the replication is working, but the textarea isn't updating when the indexer finishes its job. I'm currently rewriting the sync mechanism -- removing live sync for now until I can fix more fundamental structural issues -- so I'll ping you again here once I have something working!

**Comment by hackergrrl** [comment]
Heya @ungoldman, things should be in much better shape now if you feel like taking this for a spin again. :sunglasses:

**Comment by ungoldman** [comment]
LGTM 👍

**Comment by ungoldman** [comment]
Great work by the way :)

**Comment by hackergrrl** [comment]
Rad! Thank you.
