### ISSUE TITLE
bundle.js missing

### ISSUE THREAD

**Issue by pointlinker** [noffle/hyperpad#6]
https://github.com/noffle/hyperpad

bundle.js is missing and the link to the demo is not working.

Is P2P project saboutaged? Found another too with missing files.

**Comment by hackergrrl** [comment]
Nothing sinister, sorry. :)

1. I don't usually include `bundle.js` in my git repos.
2. My VPS is low on memory so I killed the http server and signalhub for now.

You can still build and run your own, of course.
