### ISSUE TITLE
Tab key, makes cursor out of the editor

### ISSUE THREAD

**Issue by tux-00** [noffle/hyperpad#7]
The tab key makes cusor out of the editor on the demo version.

**Comment by hackergrrl** [comment]
Thanks for the bug report @tux-00. If you felt like taking a stab at this PR I'd really appreciate it and would be happy to offer guidance.

**Comment by ansuz** [comment]
I made it so it inserts tabs instead of jumping out of the textarea, but that might annoy some people who use tabs to navigate. I'm not sure what to do about those people.

**Comment by hackergrrl** [comment]
Done: https://github.com/noffle/hyper-textarea/commit/cce31a765e99f21a2861aca0af29a7c717d284f2

**Comment by ansuz** [comment]
Nice!
